name: capstone
channels: !!python/tuple
- defaults
dependencies:
- openssl=1.0.2l=0
- pip=9.0.1=py35_1
- python=3.5.0=1
- setuptools=36.4.0=py35_1
- wheel=0.29.0=py35_0
- pip:
  - bleach==1.5.0
  - numpy==1.14.1
  - opencv-python==3.4.0.12
  - pillow==5.0.0
  - matplotlib==2.1.2
  - tensorflow-gpu==1.4.1
  - gym==0.7.4
  - universe==0.21.3

